services:
  - type: web
    name: hyper-video-app
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hyper-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
    disk:
      name: hyper-media
      mountPath: /var/data
      sizeGB: 10
databases:
  - name: hyper-db
    plan: free
