const express=require('express'),cors=require('cors'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),multer=require('multer'),path=require('path'),fs=require('fs'),crypto=require('crypto');
const {Pool}=require('pg');
const {S3Client,PutObjectCommand,DeleteObjectCommand}=require('@aws-sdk/client-s3');
const app=express(),PORT=process.env.PORT||10000,SECRET=process.env.JWT_SECRET||'dev-secret';
app.use(cors());app.use(express.json());
// Always fetch fresh feed/API data so newly published videos appear for every user/device.
app.use((req,res,next)=>{if(req.path.startsWith('/api/'))res.set('Cache-Control','no-store, no-cache, must-revalidate, proxy-revalidate');next()});
const defaultUploadDir=fs.existsSync('/var/data')?path.join('/var/data','hyper-uploads'):path.join(__dirname,'uploads');
const dir=process.env.HYPER_UPLOAD_DIR||defaultUploadDir;
fs.mkdirSync(dir,{recursive:true});
const storageConfigured=!!(process.env.STORAGE_ENDPOINT&&process.env.STORAGE_BUCKET&&process.env.STORAGE_ACCESS_KEY_ID&&process.env.STORAGE_SECRET_ACCESS_KEY&&process.env.STORAGE_PUBLIC_BASE_URL);
const s3=storageConfigured?new S3Client({endpoint:process.env.STORAGE_ENDPOINT,region:process.env.STORAGE_REGION||'auto',credentials:{accessKeyId:process.env.STORAGE_ACCESS_KEY_ID,secretAccessKey:process.env.STORAGE_SECRET_ACCESS_KEY},forcePathStyle:false}):null;
function storageKey(userId,filename){return `users/${userId}/${Date.now()}-${String(filename).replace(/[^a-zA-Z0-9._-]/g,'_')}`}
async function uploadPermanent(localPath,key,contentType){if(!storageConfigured)return null;await s3.send(new PutObjectCommand({Bucket:process.env.STORAGE_BUCKET,Key:key,Body:fs.createReadStream(localPath),ContentType:contentType||'application/octet-stream'}));return process.env.STORAGE_PUBLIC_BASE_URL.replace(/\/$/,'')+'/'+key.split('/').map(encodeURIComponent).join('/')}
async function deletePermanent(url){if(!storageConfigured||!url)return;const base=process.env.STORAGE_PUBLIC_BASE_URL.replace(/\/$/,'')+'/';if(!String(url).startsWith(base))return;const key=decodeURIComponent(String(url).slice(base.length));try{await s3.send(new DeleteObjectCommand({Bucket:process.env.STORAGE_BUCKET,Key:key}))}catch(e){console.warn('Storage delete failed:',e.message)}}
const upload=multer({storage:multer.diskStorage({destination:dir,filename:(r,f,cb)=>cb(null,Date.now()+'-'+f.originalname.replace(/[^a-zA-Z0-9._-]/g,'_'))}),limits:{fileSize:250*1024*1024}});
app.use('/uploads',express.static(dir));
const pool=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false}):null;
const demo=[
{id:1,title:'Meri Life Ka Safar | Village Vlog 2025',channel:'Hyper Vlogs',username:'hypervlogs',views:1200000,likes:28000,duration:'10:24',type:'video',thumbnail:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=80',video_url:'https://storage.googleapis.com/coverr-main/mp4/Mt_Baker.mp4'},
{id:2,title:'Mountains Calling | Travel Vlog',channel:'Explore More',username:'exploremore',views:856000,likes:19000,duration:'12:36',type:'video',thumbnail:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',video_url:'https://storage.googleapis.com/coverr-main/mp4/Footboys.mp4'},
{id:3,title:'Life is better in green! ❤️',channel:'Hyper Vlogs',views:420000,likes:42000,duration:'0:25',type:'short',thumbnail:'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=800&q=80',video_url:'https://storage.googleapis.com/coverr-main/mp4/Footboys.mp4'}];

async function db(){
 if(!pool)return;
 await pool.query(`CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,username VARCHAR(50) UNIQUE NOT NULL,email VARCHAR(160) UNIQUE NOT NULL,password_hash TEXT NOT NULL,display_name VARCHAR(100) NOT NULL,full_name VARCHAR(100),channel_name VARCHAR(100),channel_description TEXT DEFAULT '',created_at TIMESTAMPTZ DEFAULT NOW(),avatar_url TEXT DEFAULT NULL);
 CREATE TABLE IF NOT EXISTS videos(id SERIAL PRIMARY KEY,user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,title VARCHAR(200) NOT NULL,description TEXT DEFAULT '',video_url TEXT NOT NULL,thumbnail_url TEXT,type VARCHAR(20) DEFAULT 'video',category VARCHAR(30) DEFAULT 'Vlog',views INTEGER DEFAULT 0,likes INTEGER DEFAULT 0,created_at TIMESTAMPTZ DEFAULT NOW(),upload_key TEXT UNIQUE,duration_seconds INTEGER DEFAULT 0);
 ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url TEXT; ALTER TABLE users ADD COLUMN IF NOT EXISTS is_admin BOOLEAN DEFAULT FALSE; ALTER TABLE users ADD COLUMN IF NOT EXISTS is_private BOOLEAN DEFAULT FALSE; ALTER TABLE users ADD COLUMN IF NOT EXISTS is_suspended BOOLEAN DEFAULT FALSE; ALTER TABLE users ADD COLUMN IF NOT EXISTS full_name VARCHAR(100); ALTER TABLE users ADD COLUMN IF NOT EXISTS channel_name VARCHAR(100); ALTER TABLE users ADD COLUMN IF NOT EXISTS channel_description TEXT DEFAULT ''; UPDATE users SET full_name=COALESCE(full_name,display_name),channel_name=COALESCE(channel_name,display_name) WHERE full_name IS NULL OR channel_name IS NULL; ALTER TABLE videos ADD COLUMN IF NOT EXISTS category VARCHAR(30) DEFAULT 'Vlog'; ALTER TABLE videos ADD COLUMN IF NOT EXISTS upload_key TEXT; CREATE UNIQUE INDEX IF NOT EXISTS videos_upload_key_uidx ON videos(upload_key) WHERE upload_key IS NOT NULL; CREATE TABLE IF NOT EXISTS subscriptions(subscriber_id INTEGER REFERENCES users(id) ON DELETE CASCADE,channel_id INTEGER REFERENCES users(id) ON DELETE CASCADE,PRIMARY KEY(subscriber_id,channel_id));
 ALTER TABLE videos ADD COLUMN IF NOT EXISTS duration_seconds INTEGER DEFAULT 0;
 CREATE TABLE IF NOT EXISTS comments(id SERIAL PRIMARY KEY,video_id INTEGER REFERENCES videos(id) ON DELETE CASCADE,user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,text TEXT NOT NULL,created_at TIMESTAMPTZ DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS watch_history(user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,video_id INTEGER NOT NULL,watched_at TIMESTAMPTZ DEFAULT NOW(),PRIMARY KEY(user_id,video_id));
 CREATE TABLE IF NOT EXISTS liked_videos(user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,video_id INTEGER NOT NULL,liked_at TIMESTAMPTZ DEFAULT NOW(),PRIMARY KEY(user_id,video_id));
 CREATE TABLE IF NOT EXISTS saved_videos(user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,video_id INTEGER NOT NULL,saved_at TIMESTAMPTZ DEFAULT NOW(),PRIMARY KEY(user_id,video_id)); CREATE TABLE IF NOT EXISTS saved_collections(id SERIAL PRIMARY KEY,user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,name VARCHAR(100) NOT NULL,created_at TIMESTAMPTZ DEFAULT NOW(),UNIQUE(user_id,name)); CREATE TABLE IF NOT EXISTS saved_collection_items(collection_id INTEGER REFERENCES saved_collections(id) ON DELETE CASCADE,video_id INTEGER NOT NULL,saved_at TIMESTAMPTZ DEFAULT NOW(),PRIMARY KEY(collection_id,video_id)); CREATE TABLE IF NOT EXISTS ad_events(id SERIAL PRIMARY KEY,video_id INTEGER,kind VARCHAR(20) NOT NULL,created_at TIMESTAMPTZ DEFAULT NOW()); CREATE TABLE IF NOT EXISTS notifications(id BIGSERIAL PRIMARY KEY,user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,type VARCHAR(40) NOT NULL,title VARCHAR(180) NOT NULL,message TEXT NOT NULL,related_user_id INTEGER,related_video_id INTEGER,created_at TIMESTAMPTZ DEFAULT NOW(),read_at TIMESTAMPTZ); CREATE INDEX IF NOT EXISTS notifications_user_created_idx ON notifications(user_id,created_at DESC);
 CREATE TABLE IF NOT EXISTS creator_wallets(user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,enabled BOOLEAN DEFAULT FALSE,creator_share_bps INTEGER DEFAULT 7000 CHECK(creator_share_bps BETWEEN 0 AND 10000),balance_paise BIGINT DEFAULT 0,lifetime_earned_paise BIGINT DEFAULT 0,paid_out_paise BIGINT DEFAULT 0,updated_at TIMESTAMPTZ DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS hyper_admin_wallet(id INTEGER PRIMARY KEY DEFAULT 1 CHECK(id=1),balance_paise BIGINT DEFAULT 0,lifetime_earned_paise BIGINT DEFAULT 0,paid_out_paise BIGINT DEFAULT 0,updated_at TIMESTAMPTZ DEFAULT NOW());
 INSERT INTO hyper_admin_wallet(id) VALUES(1) ON CONFLICT(id) DO NOTHING;
 CREATE TABLE IF NOT EXISTS ad_revenue_ledger(id BIGSERIAL PRIMARY KEY,user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,video_id INTEGER,provider VARCHAR(40) NOT NULL,external_event_id VARCHAR(180) UNIQUE NOT NULL,gross_paise BIGINT NOT NULL,creator_paise BIGINT NOT NULL,hyper_paise BIGINT NOT NULL,impressions INTEGER DEFAULT 0,created_at TIMESTAMPTZ DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS payout_accounts(user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,provider VARCHAR(40) NOT NULL DEFAULT 'razorpayx',contact_id VARCHAR(80),fund_account_id VARCHAR(80),status VARCHAR(30) DEFAULT 'pending',updated_at TIMESTAMPTZ DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS payouts(id BIGSERIAL PRIMARY KEY,user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,amount_paise BIGINT NOT NULL,provider VARCHAR(40) NOT NULL DEFAULT 'razorpayx',provider_payout_id VARCHAR(100),status VARCHAR(30) NOT NULL DEFAULT 'created',idempotency_key VARCHAR(120) UNIQUE NOT NULL,created_at TIMESTAMPTZ DEFAULT NOW(),processed_at TIMESTAMPTZ);
 CREATE INDEX IF NOT EXISTS ad_revenue_ledger_user_created_idx ON ad_revenue_ledger(user_id,created_at DESC);
 CREATE INDEX IF NOT EXISTS payouts_user_created_idx ON payouts(user_id,created_at DESC); UPDATE creator_wallets SET creator_share_bps=7000 WHERE creator_share_bps<>7000; ${ADMIN_EMAIL ? `UPDATE users SET is_admin=TRUE WHERE LOWER(email)='${ADMIN_EMAIL.replace(/'/g,"''")}';` : ''}`);
}
const tok=u=>jwt.sign({id:u.id,username:u.username},SECRET,{expiresIn:'30d'});
function auth(req,res,next){const h=req.headers.authorization||'';try{req.user=jwt.verify(h.startsWith('Bearer ')?h.slice(7):'',SECRET);next()}catch{return res.status(401).json({message:'Login required'})}}

async function notifyUser(userId,type,title,message,relatedUserId=null,relatedVideoId=null){if(!pool||!userId)return;try{await pool.query('INSERT INTO notifications(user_id,type,title,message,related_user_id,related_video_id) VALUES($1,$2,$3,$4,$5,$6)',[userId,type,title,message,relatedUserId,relatedVideoId])}catch(e){console.warn('Notification failed:',e.message)}}
async function notifyAdmins(type,title,message,relatedUserId=null,relatedVideoId=null){if(!pool)return;try{const q=await pool.query('SELECT id FROM users WHERE is_admin=TRUE OR LOWER(email)=LOWER($1)',[ADMIN_EMAIL]);for(const r of q.rows)await notifyUser(r.id,type,title,message,relatedUserId,relatedVideoId)}catch(e){console.warn('Admin notification failed:',e.message)}}

const CREATOR_SHARE_BPS=7000; // Fixed HYPER revenue split: Creator 70% / HYPER Admin 30%
const MIN_WITHDRAWAL_PAISE=Math.max(100,Number(process.env.HYPER_MIN_WITHDRAWAL_PAISE||50000));
const MONETIZATION_LIVE=String(process.env.HYPER_MONETIZATION_ENABLED||'false').toLowerCase()==='true';
const RZP_KEY=process.env.RAZORPAYX_KEY_ID||'';
const RZP_SECRET=process.env.RAZORPAYX_KEY_SECRET||'';
const RZP_ACCOUNT=process.env.RAZORPAYX_ACCOUNT_NUMBER||'';
const ADMIN_KEY=process.env.HYPER_ADMIN_KEY||'';
const ADMIN_EMAIL=String(process.env.HYPER_ADMIN_EMAIL||'asarafalamt20@gmail.com').trim().toLowerCase();
function moneyPaise(v){return Math.round(Number(v||0));}
async function ensureWallet(userId){await pool.query('INSERT INTO creator_wallets(user_id,enabled,creator_share_bps) VALUES($1,$2,$3) ON CONFLICT(user_id) DO NOTHING',[userId,MONETIZATION_LIVE,CREATOR_SHARE_BPS]);}
function rzpAuth(){return 'Basic '+Buffer.from(RZP_KEY+':'+RZP_SECRET).toString('base64');}
async function rzp(pathname,options={}){if(!RZP_KEY||!RZP_SECRET)throw new Error('RazorpayX payout credentials are not configured');const r=await fetch('https://api.razorpay.com/v1'+pathname,{...options,headers:{Authorization:rzpAuth(),'Content-Type':'application/json',...(options.headers||{})}});const text=await r.text();let body={};try{body=JSON.parse(text)}catch{}if(!r.ok)throw new Error(body.error?.description||body.error?.reason||'RazorpayX request failed');return body;}
async function adminOnly(req,res,next){try{if(!pool)return res.status(503).json({message:'Database is not connected on the server'});const h=req.headers.authorization||'';const raw=h.startsWith('Bearer ')?h.slice(7):'';if(!raw)return res.status(401).json({message:'HYPER login required'});req.user=jwt.verify(raw,SECRET);const q=await pool.query('SELECT id,email,is_admin FROM users WHERE id=$1',[req.user.id]);const email=String(q.rows[0]?.email||'').toLowerCase();const allowed=!!q.rows[0]?.is_admin || (!!ADMIN_EMAIL && email===ADMIN_EMAIL);if(!allowed)return res.status(403).json({message:'This HYPER account is not an Admin account'});next()}catch(e){return res.status(401).json({message:'Admin login required'})}}
app.get('/api/admin/channels',adminOnly,async(req,res)=>{if(!pool)return res.json([]);try{const q=await pool.query(`SELECT u.id,u.username,u.email,u.display_name,COALESCE(u.channel_name,u.display_name) channel_name,u.is_suspended,COALESCE(cw.enabled,FALSE) monetization_enabled,(SELECT COUNT(*) FROM videos v WHERE v.user_id=u.id)::int video_count,(SELECT COUNT(*) FROM subscriptions s WHERE s.channel_id=u.id)::int subscriber_count FROM users u LEFT JOIN creator_wallets cw ON cw.user_id=u.id ORDER BY u.created_at DESC LIMIT 500`);res.json(q.rows)}catch(e){res.status(500).json({message:e.message})}});
app.post('/api/admin/channels/:id/monetization',adminOnly,async(req,res)=>{if(!pool)return res.status(503).json({message:'Database is not connected'});try{const uid=Number(req.params.id),enabled=!!req.body.enabled;await pool.query(`INSERT INTO creator_wallets(user_id,enabled,creator_share_bps) VALUES($1,$2,7000) ON CONFLICT(user_id) DO UPDATE SET enabled=EXCLUDED.enabled,creator_share_bps=7000,updated_at=NOW()`,[uid,enabled]);await notifyUser(uid,'monetization',`Monetization ${enabled?'ON':'OFF'}`,`HYPER Admin has turned your channel monetization ${enabled?'ON':'OFF'}. Creator share remains 70%.`,req.user.id);res.json({ok:true,enabled,creator_share_percent:70})}catch(e){res.status(500).json({message:e.message})}});
app.post('/api/admin/channels/:id/suspend',adminOnly,async(req,res)=>{if(!pool)return res.status(503).json({message:'Database is not connected'});try{const uid=Number(req.params.id),suspended=!!req.body.suspended;if(uid===req.user.id)return res.status(400).json({message:'Admin account cannot suspend itself'});await pool.query('UPDATE users SET is_suspended=$1 WHERE id=$2',[suspended,uid]);await notifyUser(uid,'admin_action',`Channel ${suspended?'suspended':'restored'}`,`HYPER Admin has ${suspended?'suspended':'restored'} your channel.`,req.user.id);res.json({ok:true,is_suspended:suspended})}catch(e){res.status(500).json({message:e.message})}});
app.get('/api/admin/videos',adminOnly,async(req,res)=>{if(!pool)return res.json([]);try{const q=await pool.query(`SELECT v.id,v.title,v.type,v.category,v.views,v.likes,v.created_at,v.user_id,u.username,COALESCE(u.channel_name,u.display_name) channel_name FROM videos v JOIN users u ON u.id=v.user_id ORDER BY v.created_at DESC LIMIT 300`);res.json(q.rows)}catch(e){res.status(500).json({message:e.message})}});
app.delete('/api/admin/videos/:id',adminOnly,async(req,res)=>{if(!pool)return res.status(503).json({message:'Database is not connected'});try{const q=await pool.query('SELECT v.id,v.video_url,v.thumbnail_url,v.user_id,v.title FROM videos v WHERE v.id=$1',[req.params.id]);if(!q.rows[0])return res.status(404).json({message:'Video not found'});const v=q.rows[0];await pool.query('DELETE FROM videos WHERE id=$1',[v.id]);for(const u of [v.video_url,v.thumbnail_url]){if(u&&String(u).startsWith('/uploads/')){try{fs.unlinkSync(path.join(dir,String(u).replace(/^\/uploads\//,'')))}catch{}}else await deletePermanent(u)}await notifyUser(v.user_id,'admin_action','Video removed by HYPER Admin',`Your video “${v.title}” was removed by HYPER Admin.`,req.user.id,v.id);res.json({ok:true})}catch(e){res.status(500).json({message:e.message})}});
app.post('/api/admin/message',adminOnly,async(req,res)=>{if(!pool)return res.status(503).json({message:'Database is not connected'});try{const uid=Number(req.body.user_id),title=String(req.body.title||'HYPER Admin message').trim().slice(0,180),message=String(req.body.message||'').trim();if(!uid||!message)return res.status(400).json({message:'user_id and message are required'});await notifyUser(uid,'admin_message',title,message,req.user.id);res.json({ok:true})}catch(e){res.status(500).json({message:e.message})}});
app.get('/api/admin/session',auth,async(req,res)=>{try{const q=await pool.query('SELECT id,email,username,is_admin FROM users WHERE id=$1',[req.user.id]);const email=String(q.rows[0]?.email||'').toLowerCase();const admin=!!q.rows[0]?.is_admin || (!!ADMIN_EMAIL && email===ADMIN_EMAIL);if(!admin)return res.status(403).json({message:'This HYPER account is not an Admin account'});res.json({admin:true,user:q.rows[0]})}catch(e){res.status(500).json({message:e.message})}})

app.get('/api/me/profile',auth,async(req,res)=>{if(!pool)return res.status(503).json({message:'Database is not connected on the server'});try{let q=await pool.query("SELECT id,username,email,display_name,COALESCE(full_name,display_name) full_name,COALESCE(channel_name,display_name) channel_name,COALESCE(channel_description,'') channel_description,avatar_url FROM users WHERE id=$1",[req.user.id]);res.json({user:q.rows[0]})}catch(e){res.status(500).json({message:e.message})}});
app.put('/api/me/profile',auth,async(req,res)=>{if(!pool)return res.status(503).json({message:'Database is not connected on the server'});try{let a=String(req.body.avatar_url||'');let fn=String(req.body.full_name||'').trim();let cn=String(req.body.channel_name||'').trim();let cd=String(req.body.channel_description||'').trim();if(a&&a.length>1100000)return res.status(400).json({message:'Profile picture is too large'});if(fn&&(fn.length<2||fn.length>100))return res.status(400).json({message:'User name must be 2-100 characters'});if(cn&&(cn.length<2||cn.length>100))return res.status(400).json({message:'Channel name must be 2-100 characters'});if(cd.length>500)return res.status(400).json({message:'Channel description must be 500 characters or less'});let q=await pool.query("UPDATE users SET avatar_url=COALESCE(NULLIF($1,''),avatar_url),full_name=COALESCE(NULLIF($2,''),full_name),channel_name=COALESCE(NULLIF($3,''),channel_name),channel_description=$4,display_name=COALESCE(NULLIF($3,''),display_name) WHERE id=$5 RETURNING id,username,email,display_name,COALESCE(full_name,display_name) full_name,COALESCE(channel_name,display_name) channel_name,COALESCE(channel_description,'') channel_description,avatar_url",[a,fn,cn,cd,req.user.id]);res.json({user:q.rows[0]})}catch(e){res.status(500).json({message:e.message})}});
app.get('/api/health',(r,s)=>s.json({ok:true,app:'HYPER',storage:storageConfigured?'permanent':'local',message:storageConfigured?'Permanent storage enabled':(dir.startsWith('/var/data')?'Persistent Render disk storage enabled':'Local disk storage; configure HYPER_UPLOAD_DIR or permanent object storage for deployment-safe media')}));
app.get('/api/studio/overview',auth,async(req,res)=>{
 if(!pool)return res.json({channel:{username:req.user.username,channel_name:req.user.username,subscriber_count:0},stats:{uploads:0,videos:0,shorts:0,views:0,likes:0},topVideos:[],monthlyViews:[],monetization:{enabled:false,balance:0,lifetime_earned:0,paid_out:0,creator_share_percent:CREATOR_SHARE_BPS/100},ads:{estimated_revenue:0,impressions:0}});
 try{
  await ensureWallet(req.user.id);
  const [profile,stats,top,months,wallet,ads]=await Promise.all([
   pool.query(`SELECT username,display_name,COALESCE(channel_name,display_name) channel_name,COALESCE(channel_description,'') channel_description,avatar_url,(SELECT COUNT(*) FROM subscriptions s WHERE s.channel_id=u.id)::int subscriber_count FROM users u WHERE u.id=$1`,[req.user.id]),
   pool.query(`SELECT COUNT(*)::int uploads,COUNT(*) FILTER(WHERE type='video')::int videos,COUNT(*) FILTER(WHERE type='short')::int shorts,COALESCE(SUM(views),0)::int views,COALESCE(SUM(likes),0)::int likes FROM videos WHERE user_id=$1`,[req.user.id]),
   pool.query(`SELECT id,title,views,likes,type,category,thumbnail_url,created_at FROM videos WHERE user_id=$1 ORDER BY views DESC,created_at DESC LIMIT 10`,[req.user.id]),
   pool.query(`SELECT TO_CHAR(DATE_TRUNC('month',created_at),'Mon YYYY') AS "month",COALESCE(SUM(views),0)::int views FROM videos WHERE user_id=$1 GROUP BY DATE_TRUNC('month',created_at) ORDER BY DATE_TRUNC('month',created_at) DESC LIMIT 6`,[req.user.id]),
   pool.query(`SELECT enabled,creator_share_bps,balance_paise,lifetime_earned_paise,paid_out_paise FROM creator_wallets WHERE user_id=$1`,[req.user.id]),
   pool.query(`SELECT COALESCE(SUM(gross_paise),0)::bigint gross_paise,COALESCE(SUM(creator_paise),0)::bigint creator_paise,COALESCE(SUM(impressions),0)::bigint impressions FROM ad_revenue_ledger WHERE user_id=$1`,[req.user.id])
  ]);
  const w=wallet.rows[0]||{},a=ads.rows[0]||{};
  res.json({channel:profile.rows[0],stats:stats.rows[0],topVideos:top.rows,monthlyViews:months.rows.reverse(),monetization:{enabled:!!w.enabled,balance:Number(w.balance_paise||0)/100,lifetime_earned:Number(w.lifetime_earned_paise||0)/100,paid_out:Number(w.paid_out_paise||0)/100,creator_share_percent:Number(w.creator_share_bps||CREATOR_SHARE_BPS)/100},ads:{estimated_revenue:Number(a.creator_paise||0)/100,impressions:Number(a.impressions||0),gross_revenue:Number(a.gross_paise||0)/100}})
 }catch(e){res.status(500).json({message:e.message})}
});
app.get('/api/studio/content',auth,async(req,res)=>{if(!pool)return res.json([]);try{let q=await pool.query(`SELECT id,title,type,category,views,likes,duration_seconds,created_at,thumbnail_url,video_url FROM videos WHERE user_id=$1 ORDER BY created_at DESC`,[req.user.id]);res.json(q.rows)}catch(e){res.status(500).json({message:e.message})}});


app.post('/api/auth/register',async(req,res)=>{
 try{
  if(!pool)return res.status(503).json({message:'Database is not connected on the server'});
  let {username,email,password,displayName}=req.body;
  username=(username||'').trim(); email=(email||'').trim().toLowerCase(); displayName=(displayName||username).trim();
  if(!username||!email||!password)return res.status(400).json({message:'Name, email and password are required'});
  if(password.length<6)return res.status(400).json({message:'Password must be at least 6 characters'});
  if(!/^[a-zA-Z0-9_]{3,50}$/.test(username))return res.status(400).json({message:'Username: 3-50 letters, numbers or _ only'});
  let h=await bcrypt.hash(password,10);
  let q=await pool.query('INSERT INTO users(username,email,password_hash,display_name,full_name,channel_name) VALUES($1,$2,$3,$4,$4,$4) RETURNING id,username,email,display_name,full_name,channel_name,channel_description,avatar_url',[username.toLowerCase(),email,h,displayName]);
  let u=q.rows[0]; res.json({user:u,token:tok(u)});
 }catch(e){res.status(400).json({message:e.code==='23505'?'Username or email already exists':e.message})}
});
app.post('/api/auth/login',async(req,res)=>{
 try{
  if(!pool)return res.status(503).json({message:'Database is not connected on the server'});
  let email=(req.body.email||'').trim().toLowerCase(), q=await pool.query('SELECT * FROM users WHERE email=$1',[email]),u=q.rows[0];
  if(!u||!(await bcrypt.compare(req.body.password||'',u.password_hash)))return res.status(401).json({message:'Invalid email or password'});
  let x={id:u.id,username:u.username,email:u.email,display_name:u.display_name,full_name:u.full_name||u.display_name,channel_name:u.channel_name||u.display_name,channel_description:u.channel_description||'',avatar_url:u.avatar_url,is_private:!!u.is_private,is_admin:!!u.is_admin || (!!ADMIN_EMAIL && email===ADMIN_EMAIL),is_suspended:!!u.is_suspended};res.json({user:x,token:tok(x)});
 }catch(e){res.status(500).json({message:e.message})}
});
app.get('/api/me/notifications',auth,async(req,res)=>{if(!pool)return res.json({items:[],unread:0});try{let q=await pool.query('SELECT id,type,title,message,related_user_id,related_video_id,created_at,read_at FROM notifications WHERE user_id=$1 ORDER BY created_at DESC LIMIT 100',[req.user.id]);let u=q.rows.filter(x=>!x.read_at).length;res.json({items:q.rows,unread:u})}catch(e){res.status(500).json({message:e.message})}});
app.post('/api/me/notifications/read-all',auth,async(req,res)=>{if(!pool)return res.json({ok:true});try{await pool.query('UPDATE notifications SET read_at=NOW() WHERE user_id=$1 AND read_at IS NULL',[req.user.id]);res.json({ok:true})}catch(e){res.status(500).json({message:e.message})}});

app.put('/api/me/settings',auth,async(req,res)=>{if(!pool)return res.json({is_private:!!req.body.is_private});try{let v=!!req.body.is_private;let q=await pool.query('UPDATE users SET is_private=$1 WHERE id=$2 RETURNING is_private',[v,req.user.id]);res.json({is_private:!!q.rows[0]?.is_private})}catch(e){res.status(500).json({message:e.message})}});
app.get('/api/channels/:username',async(req,res)=>{
 if(!pool){let v=demo.find(x=>(x.username||'').toLowerCase()===req.params.username.toLowerCase());return v?res.json({username:v.username,display_name:v.channel,channel_name:v.channel,avatar_url:v.avatar_url||null,subscriber_count:0}):res.status(404).json({message:'Channel not found'})}
 try{let q=await pool.query("SELECT u.id,u.username,u.email,u.display_name,COALESCE(u.full_name,u.display_name) full_name,COALESCE(u.channel_name,u.display_name) channel_name,COALESCE(u.channel_description,'') channel_description,u.avatar_url,u.is_private,(SELECT COUNT(*) FROM subscriptions s WHERE s.channel_id=u.id) subscriber_count FROM users u WHERE LOWER(u.username)=LOWER($1)",[req.params.username]);if(!q.rows[0])return res.status(404).json({message:'Channel not found'});res.json(q.rows[0])}catch(e){res.status(500).json({message:e.message})}
});
app.get('/api/me/subscriptions',auth,async(req,res)=>{if(!pool)return res.json([]);try{let q=await pool.query(`SELECT u.id,u.username,u.email,u.display_name,COALESCE(u.full_name,u.display_name) full_name,COALESCE(u.channel_name,u.display_name) channel_name,COALESCE(u.channel_description,'') channel_description,u.avatar_url,(SELECT COUNT(*) FROM subscriptions s2 WHERE s2.channel_id=u.id) subscriber_count FROM subscriptions s JOIN users u ON u.id=s.channel_id WHERE s.subscriber_id=$1 ORDER BY u.channel_name`,[req.user.id]);res.json(q.rows)}catch(e){res.status(500).json({message:e.message})}});
app.get('/api/me/subscription-videos',auth,async(req,res)=>{if(!pool)return res.json([]);try{let q=await pool.query(`SELECT v.*,u.username,u.display_name channel,u.avatar_url,(SELECT COUNT(*) FROM subscriptions s2 WHERE s2.channel_id=u.id)::int subscriber_count FROM videos v JOIN users u ON u.id=v.user_id JOIN subscriptions s ON s.channel_id=u.id WHERE s.subscriber_id=$1 ORDER BY v.created_at DESC`,[req.user.id]);res.json(q.rows)}catch(e){res.status(500).json({message:e.message})}});
app.get('/api/channels/:username/subscribed',auth,async(req,res)=>{if(!pool)return res.json({subscribed:false});try{let q=await pool.query('SELECT u.id,(SELECT COUNT(*) FROM subscriptions s2 WHERE s2.channel_id=u.id) subscriber_count,EXISTS(SELECT 1 FROM subscriptions s WHERE s.subscriber_id=$2 AND s.channel_id=u.id) subscribed FROM users u WHERE LOWER(u.username)=LOWER($1)',[req.params.username,req.user.id]);if(!q.rows[0])return res.status(404).json({message:'Channel not found'});res.json(q.rows[0])}catch(e){res.status(500).json({message:e.message})}});
app.get('/api/search',async(req,res)=>{
 const q=String(req.query.q||'').trim();
 if(!q)return res.json({channels:[],videos:[]});
 if(!pool){
  const x=q.toLowerCase();
  const channels=demo.filter(v=>(v.channel||'').toLowerCase().includes(x)).map(v=>({username:v.username,display_name:v.channel,channel_name:v.channel,avatar_url:v.avatar_url||null,subscriber_count:0}));
  const seen=new Set(); const cs=channels.filter(c=>{if(seen.has(c.username))return false;seen.add(c.username);return true});
  return res.json({channels:cs,videos:demo.filter(v=>((v.title||'')+' '+(v.channel||'')+' '+(v.category||'')).toLowerCase().includes(x))});
 }
 try{
  const like='%'+q.replace(/[%_]/g,'\$&')+'%';
  const cr=await pool.query(`SELECT u.username,u.display_name,u.channel_name,u.avatar_url,(SELECT COUNT(*) FROM subscriptions s WHERE s.channel_id=u.id)::int subscriber_count
    FROM users u WHERE u.is_private IS NOT TRUE AND (u.username ILIKE $1 ESCAPE '\\' OR u.display_name ILIKE $1 ESCAPE '\\' OR u.channel_name ILIKE $1 ESCAPE '\\')
    ORDER BY u.channel_name ASC LIMIT 20`,[like]);
  const vr=await pool.query(`SELECT v.*,u.username,u.display_name channel,u.channel_name,u.avatar_url,(SELECT COUNT(*) FROM subscriptions s WHERE s.channel_id=u.id)::int subscriber_count
    FROM videos v JOIN users u ON u.id=v.user_id
    WHERE u.is_private IS NOT TRUE AND (v.title ILIKE $1 ESCAPE '\\' OR v.description ILIKE $1 ESCAPE '\\' OR u.username ILIKE $1 ESCAPE '\\' OR u.display_name ILIKE $1 ESCAPE '\\' OR u.channel_name ILIKE $1 ESCAPE '\\')
    ORDER BY v.created_at DESC LIMIT 100`,[like]);
  res.json({channels:cr.rows,videos:vr.rows});
 }catch(e){res.status(500).json({message:e.message})}
});
app.get('/api/videos',async(req,res)=>{
 const type=req.query.type==='short'?'short':req.query.type==='video'?'video':null;
 const category=String(req.query.category||'').trim();
 if(!pool){
  let list=demo.slice();
  if(type)list=list.filter(x=>x.type===type);
  if(category==='Popular') list=list.filter(x=>x.type!=='short').sort((a,b)=>(Number(b.views||0)+Number(b.likes||0)*25)-(Number(a.views||0)+Number(a.likes||0)*25));
  else if(category&&category!=='All')list=list.filter(x=>(x.category||'Discover').toLowerCase()===category.toLowerCase());
  return res.json(list);
 }
 try{
  const params=[]; const where=[];
  if(type){params.push(type);where.push(`v.type=$${params.length}`)}
  if(category&&category!=='All'&&category!=='Popular'){params.push(category);where.push(`LOWER(v.category)=LOWER($${params.length})`)}
  const privacyClause='u.is_private IS NOT TRUE'; where.push(privacyClause);
  const order=category==='Popular' ? 'ORDER BY ((v.views::numeric)+(v.likes::numeric*25)) DESC, v.created_at DESC' : 'ORDER BY v.created_at DESC';
  const q=await pool.query(`SELECT v.*,u.username,u.display_name channel,u.channel_name,u.avatar_url,(SELECT COUNT(*) FROM subscriptions s WHERE s.channel_id=u.id)::int subscriber_count FROM videos v JOIN users u ON u.id=v.user_id WHERE ${where.join(' AND ')} ${order}`,params);
  res.json(q.rows);
 }catch(e){res.status(500).json({message:e.message})}
});

app.get('/api/videos/:id',async(req,res)=>{
 if(!pool){let v=demo.find(x=>String(x.id)===req.params.id);return v?res.json(v):res.status(404).json({message:'Not found'})}
 try{let q=await pool.query('SELECT v.*,u.username,u.display_name channel,u.avatar_url,(SELECT COUNT(*) FROM subscriptions s WHERE s.channel_id=u.id)::int subscriber_count FROM videos v JOIN users u ON u.id=v.user_id WHERE v.id=$1',[req.params.id]);if(!q.rows[0])return res.status(404).json({message:'Not found'});await pool.query('UPDATE videos SET views=views+1 WHERE id=$1',[req.params.id]);res.json(q.rows[0])}
 catch(e){res.status(500).json({message:e.message})}
});
app.post('/api/videos',auth,upload.fields([{name:'video',maxCount:1},{name:'thumbnail',maxCount:1}]),async(req,res)=>{
 if(pool){const uq=await pool.query('SELECT is_suspended,email,channel_name,display_name FROM users WHERE id=$1',[req.user.id]);if(uq.rows[0]?.is_suspended)return res.status(403).json({message:'Your channel is currently suspended by HYPER Admin'});}

 if(!pool)return res.status(503).json({message:'Database is not connected. Add DATABASE_URL and restart the server.'});
 const vf=req.files?.video?.[0];
 if(!vf)return res.status(400).json({message:'Video required'});
 const allowed=['Discover','Popular','Entertainment','News','Education','Sports','Music','Gaming','Lifestyle','Creator'];
 const cat=allowed.includes(req.body.category)?req.body.category:'Discover';
 const durationSeconds=Math.max(0,Math.round(Number(req.body.duration_seconds||0)));
 try{let v='/uploads/'+vf.filename,t=req.files.thumbnail?.[0]?'/uploads/'+req.files.thumbnail[0].filename:null;
 const uploadKey=String(req.body.upload_id||'').trim()||null;
 if(uploadKey){const existing=await pool.query('SELECT * FROM videos WHERE upload_key=$1 LIMIT 1',[uploadKey]);if(existing.rows[0]){try{fs.unlinkSync(path.join(dir,vf.filename));if(req.files.thumbnail?.[0])fs.unlinkSync(path.join(dir,req.files.thumbnail[0].filename))}catch{}return res.status(200).json(existing.rows[0])}}
 if(storageConfigured){
   const vk=storageKey(req.user.id,vf.originalname); v=await uploadPermanent(path.join(dir,vf.filename),vk,vf.mimetype);
   let thumb=req.files.thumbnail?.[0]; if(thumb){const tk=storageKey(req.user.id,thumb.originalname);t=await uploadPermanent(path.join(dir,thumb.filename),tk,thumb.mimetype)}
 }
 let q=await pool.query('INSERT INTO videos(user_id,title,description,video_url,thumbnail_url,type,category,upload_key,duration_seconds) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[req.user.id,String(req.body.title||'Untitled').slice(0,200),req.body.description||'',v,t,req.body.type==='short'?'short':'video',cat,uploadKey,durationSeconds]);
 if(storageConfigured){try{fs.unlinkSync(path.join(dir,vf.filename));if(req.files.thumbnail?.[0])fs.unlinkSync(path.join(dir,req.files.thumbnail[0].filename))}catch{}}
 await notifyAdmins('video_upload','New video uploaded',`Channel @${req.user.username} uploaded “${q.rows[0].title}”.`,req.user.id,q.rows[0].id);
 res.status(201).json(q.rows[0])}
 catch(e){try{fs.unlinkSync(path.join(dir,vf.filename));if(req.files.thumbnail?.[0])fs.unlinkSync(path.join(dir,req.files.thumbnail[0].filename))}catch{}console.error('Publish error:',e);res.status(500).json({message:storageConfigured?'Permanent storage upload failed. Please try again.':'Publish failed. Please try again.'})}
});
app.put('/api/videos/:id',auth,async(req,res)=>{if(!pool)return res.status(503).json({message:'Database is not connected'});try{let q=await pool.query('SELECT id,title,description,category,type FROM videos WHERE id=$1 AND user_id=$2',[req.params.id,req.user.id]);if(!q.rows[0])return res.status(404).json({message:'Video not found or not yours'});let title=String(req.body.title??q.rows[0].title).trim(),description=String((req.body.description??q.rows[0].description)||'').trim(),category=String((req.body.category??q.rows[0].category)||'Discover').trim();if(!title||title.length>200)return res.status(400).json({message:'Title must be 1-200 characters'});if(description.length>5000)return res.status(400).json({message:'Description is too long'});let r=await pool.query('UPDATE videos SET title=$1,description=$2,category=$3 WHERE id=$4 AND user_id=$5 RETURNING *',[title,description,category,req.params.id,req.user.id]);res.json(r.rows[0])}catch(e){res.status(500).json({message:e.message})}});
app.delete('/api/videos/:id',auth,async(req,res)=>{if(!pool)return res.status(503).json({message:'Database is not connected'});try{let q=await pool.query('SELECT video_url,thumbnail_url FROM videos WHERE id=$1 AND user_id=$2',[req.params.id,req.user.id]);if(!q.rows[0])return res.status(404).json({message:'Video not found or not yours'});await pool.query('DELETE FROM videos WHERE id=$1 AND user_id=$2',[req.params.id,req.user.id]);for(const u of [q.rows[0].video_url,q.rows[0].thumbnail_url]){if(u&&String(u).startsWith('/uploads/')){try{fs.unlinkSync(path.join(dir,String(u).replace(/^\/uploads\//,'')))}catch{}}else await deletePermanent(u)}res.json({deleted:true})}catch(e){res.status(500).json({message:e.message})}});
app.post('/api/ads/event',async(req,res)=>{
 try{if(pool){const id=Number(req.body.video_id);const kind=String(req.body.kind||'impression').slice(0,20);await pool.query('INSERT INTO ad_events(video_id,kind) VALUES($1,$2)',[Number.isFinite(id)?id:null,kind])}res.json({ok:true})}catch(e){res.status(500).json({message:e.message})}
});
app.post('/api/videos/:id/view',async(req,res)=>{
 if(!pool){let v=demo.find(x=>String(x.id)===String(req.params.id));return v?res.json({views:(v.views||0)+1}):res.status(404).json({message:'Not found'})}
 try{let q=await pool.query('UPDATE videos SET views=views+1 WHERE id=$1 RETURNING views',[req.params.id]);if(!q.rows[0])return res.status(404).json({message:'Not found'});res.json({views:q.rows[0].views})}catch(e){res.status(500).json({message:e.message})}
});
app.post('/api/videos/:id/like',auth,async(req,res)=>{
 if(!pool)return res.json({likes:0,liked:true});
 try{
  let x=await pool.query('SELECT 1 FROM liked_videos WHERE user_id=$1 AND video_id=$2',[req.user.id,req.params.id]);
  if(x.rowCount){await pool.query('DELETE FROM liked_videos WHERE user_id=$1 AND video_id=$2',[req.user.id,req.params.id]);let q=await pool.query('UPDATE videos SET likes=GREATEST(likes-1,0) WHERE id=$1 RETURNING likes',[req.params.id]);return res.json({likes:q.rows[0].likes,liked:false})}
  await pool.query('INSERT INTO liked_videos(user_id,video_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[req.user.id,req.params.id]);let q=await pool.query('UPDATE videos SET likes=likes+1 WHERE id=$1 RETURNING likes',[req.params.id]);res.json({likes:q.rows[0].likes,liked:true})
 }catch(e){res.status(500).json({message:e.message})}
});
app.post('/api/channels/:username/subscribe',auth,async(req,res)=>{
 if(!pool)return res.json({subscribed:true,subscriber_count:0});
 try{let q=await pool.query('SELECT id FROM users WHERE LOWER(username)=LOWER($1)',[req.params.username]);if(!q.rows[0])return res.status(404).json({message:'Channel not found'});let c=q.rows[0].id;if(c===req.user.id)return res.status(400).json({message:'Cannot subscribe to yourself'});let x=await pool.query('SELECT 1 FROM subscriptions WHERE subscriber_id=$1 AND channel_id=$2',[req.user.id,c]);let subscribed;if(x.rowCount){await pool.query('DELETE FROM subscriptions WHERE subscriber_id=$1 AND channel_id=$2',[req.user.id,c]);subscribed=false}else{await pool.query('INSERT INTO subscriptions(subscriber_id,channel_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[req.user.id,c]);subscribed=true}let n=await pool.query('SELECT COUNT(*)::int subscriber_count FROM subscriptions WHERE channel_id=$1',[c]);res.json({subscribed,subscriber_count:n.rows[0].subscriber_count})}catch(e){res.status(500).json({message:e.message})}
});
app.post('/api/videos/:id/subscribe',auth,async(req,res)=>{
 if(!pool)return res.json({subscribed:true,subscriber_count:0});
 try{let q=await pool.query('SELECT u.username FROM videos v JOIN users u ON u.id=v.user_id WHERE v.id=$1',[req.params.id]);if(!q.rows[0])return res.status(404).json({message:'Not found'});let c=await pool.query('SELECT id FROM users WHERE LOWER(username)=LOWER($1)',[q.rows[0].username]);let cid=c.rows[0].id;if(cid===req.user.id)return res.status(400).json({message:'Cannot subscribe to yourself'});let x=await pool.query('SELECT 1 FROM subscriptions WHERE subscriber_id=$1 AND channel_id=$2',[req.user.id,cid]);let subscribed;if(x.rowCount){await pool.query('DELETE FROM subscriptions WHERE subscriber_id=$1 AND channel_id=$2',[req.user.id,cid]);subscribed=false}else{await pool.query('INSERT INTO subscriptions(subscriber_id,channel_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[req.user.id,cid]);subscribed=true}let n=await pool.query('SELECT COUNT(*)::int subscriber_count FROM subscriptions WHERE channel_id=$1',[cid]);res.json({subscribed,subscriber_count:n.rows[0].subscriber_count})}catch(e){res.status(500).json({message:e.message})}
});
app.post('/api/videos/:id/history',auth,async(req,res)=>{if(!pool)return res.json({ok:true});try{await pool.query('INSERT INTO watch_history(user_id,video_id,watched_at) VALUES($1,$2,NOW()) ON CONFLICT(user_id,video_id) DO UPDATE SET watched_at=NOW()',[req.user.id,req.params.id]);res.json({ok:true})}catch(e){res.status(500).json({message:e.message})}});
app.get('/api/me/history',auth,async(req,res)=>{if(!pool)return res.json([]);try{let q=await pool.query(`SELECT v.*,u.username,u.display_name channel,u.avatar_url FROM watch_history h JOIN videos v ON v.id=h.video_id LEFT JOIN users u ON u.id=v.user_id WHERE h.user_id=$1 ORDER BY h.watched_at DESC LIMIT 100`,[req.user.id]);res.json(q.rows)}catch(e){res.status(500).json({message:e.message})}});
app.delete('/api/me/history/:videoId',auth,async(req,res)=>{if(!pool)return res.json({ok:true});try{await pool.query('DELETE FROM watch_history WHERE user_id=$1 AND video_id=$2',[req.user.id,req.params.videoId]);res.json({ok:true})}catch(e){res.status(500).json({message:e.message})}});
app.delete('/api/me/history',auth,async(req,res)=>{if(!pool)return res.json({ok:true});try{await pool.query('DELETE FROM watch_history WHERE user_id=$1',[req.user.id]);res.json({ok:true})}catch(e){res.status(500).json({message:e.message})}});
app.get('/api/me/liked',auth,async(req,res)=>{if(!pool)return res.json([]);try{let q=await pool.query(`SELECT v.*,u.username,u.display_name channel,u.avatar_url FROM liked_videos l JOIN videos v ON v.id=l.video_id LEFT JOIN users u ON u.id=v.user_id WHERE l.user_id=$1 ORDER BY l.liked_at DESC LIMIT 100`,[req.user.id]);res.json(q.rows)}catch(e){res.status(500).json({message:e.message})}});
app.get('/api/me/videos',auth,async(req,res)=>{if(!pool)return res.json([]);try{let q=await pool.query('SELECT v.*,u.username,u.display_name channel,u.avatar_url,(SELECT COUNT(*) FROM subscriptions s WHERE s.channel_id=u.id)::int subscriber_count FROM videos v JOIN users u ON u.id=v.user_id WHERE v.user_id=$1 ORDER BY v.created_at DESC',[req.user.id]);res.json(q.rows)}catch(e){res.status(500).json({message:e.message})}});
app.post('/api/videos/:id/save',auth,async(req,res)=>{if(!pool)return res.json({saved:true});try{let x=await pool.query('SELECT 1 FROM saved_videos WHERE user_id=$1 AND video_id=$2',[req.user.id,req.params.id]);if(x.rowCount){await pool.query('DELETE FROM saved_videos WHERE user_id=$1 AND video_id=$2',[req.user.id,req.params.id]);return res.json({saved:false})}await pool.query('INSERT INTO saved_videos(user_id,video_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[req.user.id,req.params.id]);res.json({saved:true})}catch(e){res.status(500).json({message:e.message})}});
app.get('/api/me/saved',auth,async(req,res)=>{if(!pool)return res.json([]);try{let q=await pool.query(`SELECT v.*,u.username,u.display_name channel,u.avatar_url FROM saved_videos s JOIN videos v ON v.id=s.video_id LEFT JOIN users u ON u.id=v.user_id WHERE s.user_id=$1 ORDER BY s.saved_at DESC LIMIT 100`,[req.user.id]);res.json(q.rows)}catch(e){res.status(500).json({message:e.message})}});
app.get('/api/me/saved-collections',auth,async(req,res)=>{if(!pool)return res.json([]);try{let q=await pool.query(`SELECT c.id,c.name,c.created_at,COUNT(i.video_id)::int video_count FROM saved_collections c LEFT JOIN saved_collection_items i ON i.collection_id=c.id WHERE c.user_id=$1 GROUP BY c.id ORDER BY c.created_at DESC`,[req.user.id]);res.json(q.rows)}catch(e){res.status(500).json({message:e.message})}});
app.post('/api/me/saved-collections',auth,async(req,res)=>{if(!pool)return res.json({id:0,name:String(req.body.name||'Saved')});try{let name=String(req.body.name||'').trim();if(name.length<1||name.length>100)return res.status(400).json({message:'Save file name must be 1-100 characters'});let q=await pool.query('INSERT INTO saved_collections(user_id,name) VALUES($1,$2) ON CONFLICT(user_id,name) DO UPDATE SET name=EXCLUDED.name RETURNING id,name',[req.user.id,name]);res.json(q.rows[0])}catch(e){res.status(500).json({message:e.message})}});
app.get('/api/me/saved-collections/:id',auth,async(req,res)=>{if(!pool)return res.json([]);try{let q=await pool.query(`SELECT v.*,u.username,u.display_name channel,u.avatar_url FROM saved_collection_items i JOIN saved_collections c ON c.id=i.collection_id JOIN videos v ON v.id=i.video_id LEFT JOIN users u ON u.id=v.user_id WHERE c.id=$1 AND c.user_id=$2 ORDER BY i.saved_at DESC`,[req.params.id,req.user.id]);res.json(q.rows)}catch(e){res.status(500).json({message:e.message})}});
app.delete('/api/me/saved-collections/:id',auth,async(req,res)=>{if(!pool)return res.json({ok:true});try{await pool.query('DELETE FROM saved_collections WHERE id=$1 AND user_id=$2',[req.params.id,req.user.id]);res.json({ok:true})}catch(e){res.status(500).json({message:e.message})}});
app.post('/api/me/saved-collections/:id/videos/:videoId',auth,async(req,res)=>{if(!pool)return res.json({saved:true});try{let c=await pool.query('SELECT id FROM saved_collections WHERE id=$1 AND user_id=$2',[req.params.id,req.user.id]);if(!c.rowCount)return res.status(404).json({message:'Save file not found'});await pool.query('INSERT INTO saved_collection_items(collection_id,video_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[req.params.id,req.params.videoId]);res.json({saved:true})}catch(e){res.status(500).json({message:e.message})}});
app.delete('/api/me/saved-collections/:id/videos/:videoId',auth,async(req,res)=>{if(!pool)return res.json({saved:false});try{await pool.query('DELETE FROM saved_collection_items i USING saved_collections c WHERE i.collection_id=c.id AND c.id=$1 AND c.user_id=$2 AND i.video_id=$3',[req.params.id,req.user.id,req.params.videoId]);res.json({saved:false})}catch(e){res.status(500).json({message:e.message})}});



app.get('/api/studio/earnings',auth,async(req,res)=>{if(!pool)return res.status(503).json({message:'Database is not connected on the server'});try{await ensureWallet(req.user.id);const [w,l,p]=await Promise.all([pool.query('SELECT enabled,creator_share_bps,balance_paise,lifetime_earned_paise,paid_out_paise FROM creator_wallets WHERE user_id=$1',[req.user.id]),pool.query('SELECT provider,external_event_id,gross_paise,creator_paise,hyper_paise,impressions,created_at FROM ad_revenue_ledger WHERE user_id=$1 ORDER BY created_at DESC LIMIT 100',[req.user.id]),pool.query('SELECT amount_paise,provider,provider_payout_id,status,created_at,processed_at FROM payouts WHERE user_id=$1 ORDER BY created_at DESC LIMIT 50',[req.user.id])]);let x=w.rows[0];res.json({monetization:{enabled:!!x.enabled,creator_share_percent:Number(x.creator_share_bps)/100,balance:Number(x.balance_paise)/100,lifetime_earned:Number(x.lifetime_earned_paise)/100,paid_out:Number(x.paid_out_paise)/100,min_withdrawal:MIN_WITHDRAWAL_PAISE/100},ledger:l.rows.map(r=>({...r,gross:Number(r.gross_paise)/100,creator:Number(r.creator_paise)/100,hyper:Number(r.hyper_paise)/100})),payouts:p.rows.map(r=>({...r,amount:Number(r.amount_paise)/100}))})}catch(e){res.status(500).json({message:e.message})}});
app.get('/api/studio/payout-account',auth,async(req,res)=>{if(!pool)return res.json({configured:false});try{let q=await pool.query('SELECT provider,contact_id,fund_account_id,status,updated_at FROM payout_accounts WHERE user_id=$1',[req.user.id]);res.json({configured:!!q.rows[0]?.fund_account_id,status:q.rows[0]?.status||'not_configured',provider:q.rows[0]?.provider||'razorpayx'})}catch(e){res.status(500).json({message:e.message})}});
app.post('/api/studio/payout-account',auth,async(req,res)=>{if(!pool)return res.status(503).json({message:'Database is not connected on the server'});try{const fund=String(req.body.fund_account_id||'').trim();const contact=String(req.body.contact_id||'').trim();if(!fund)return res.status(400).json({message:'RazorpayX fund account ID is required'});await pool.query(`INSERT INTO payout_accounts(user_id,provider,contact_id,fund_account_id,status,updated_at) VALUES($1,'razorpayx',$2,$3,'ready',NOW()) ON CONFLICT(user_id) DO UPDATE SET contact_id=EXCLUDED.contact_id,fund_account_id=EXCLUDED.fund_account_id,status='ready',updated_at=NOW()`,[req.user.id,contact||null,fund]);res.json({ok:true,status:'ready'})}catch(e){res.status(500).json({message:e.message})}});
app.post('/api/studio/withdraw',auth,async(req,res)=>{if(!pool)return res.status(503).json({message:'Database is not connected on the server'});const client=await pool.connect();try{const amount=moneyPaise(req.body.amount_paise);if(!Number.isFinite(amount)||amount<MIN_WITHDRAWAL_PAISE)return res.status(400).json({message:`Minimum withdrawal is ₹${(MIN_WITHDRAWAL_PAISE/100).toFixed(2)}`});await client.query('BEGIN');await client.query('SELECT pg_advisory_xact_lock($1)',[req.user.id]);await ensureWallet(req.user.id);const w=(await client.query('SELECT balance_paise FROM creator_wallets WHERE user_id=$1 FOR UPDATE',[req.user.id])).rows[0];if(Number(w.balance_paise)<amount){await client.query('ROLLBACK');return res.status(400).json({message:'Insufficient available balance'});}const pa=(await client.query('SELECT fund_account_id FROM payout_accounts WHERE user_id=$1 AND status=\'ready\'',[req.user.id])).rows[0];if(!pa?.fund_account_id){await client.query('ROLLBACK');return res.status(400).json({message:'Set up your payout account first'});}if(!RZP_KEY||!RZP_SECRET||!RZP_ACCOUNT){await client.query('ROLLBACK');return res.status(503).json({message:'RazorpayX live payout configuration is not complete'});}const idem=crypto.randomUUID();const row=(await client.query('INSERT INTO payouts(user_id,amount_paise,provider,status,idempotency_key) VALUES($1,$2,\'razorpayx\',\'created\',$3) RETURNING id',[req.user.id,amount,idem])).rows[0];await client.query('UPDATE creator_wallets SET balance_paise=balance_paise-$1,paid_out_paise=paid_out_paise+$1,updated_at=NOW() WHERE user_id=$2',[amount,req.user.id]);await client.query('COMMIT');let rp;try{rp=await rzp('/payouts',{method:'POST',headers:{'X-Payout-Idempotency':idem},body:JSON.stringify({account_number:RZP_ACCOUNT,fund_account_id:pa.fund_account_id,amount,currency:'INR',mode:String(req.body.mode||'IMPS').toUpperCase(),purpose:'payout',queue_if_low_balance:true,reference_id:'HYPER-'+row.id})})}catch(e){await pool.query('UPDATE payouts SET status=\'failed\',processed_at=NOW() WHERE id=$1',[row.id]);await pool.query('UPDATE creator_wallets SET balance_paise=balance_paise+$1,paid_out_paise=GREATEST(paid_out_paise-$1,0),updated_at=NOW() WHERE user_id=$2',[amount,req.user.id]);return res.status(502).json({message:e.message})}await pool.query('UPDATE payouts SET provider_payout_id=$1,status=$2,processed_at=NOW() WHERE id=$3',[rp.id||null,rp.status||'processing',row.id]);res.json({ok:true,payout_id:rp.id,status:rp.status||'processing',amount:amount/100})}catch(e){try{await client.query('ROLLBACK')}catch{}res.status(500).json({message:e.message})}finally{client.release()}});
app.post('/api/admin/monetization/enable',adminOnly,async(req,res)=>{if(!pool)return res.status(503).json({message:'Database is not connected on the server'});try{const uid=Number(req.body.user_id);const enabled=req.body.enabled!==false;const share=7000; await pool.query(`INSERT INTO creator_wallets(user_id,enabled,creator_share_bps) VALUES($1,$2,$3) ON CONFLICT(user_id) DO UPDATE SET enabled=EXCLUDED.enabled,creator_share_bps=EXCLUDED.creator_share_bps,updated_at=NOW()`,[uid,enabled,share]);await notifyUser(uid,'monetization',`Monetization ${enabled?'ON':'OFF'}`,`HYPER Admin has turned your channel monetization ${enabled?'ON':'OFF'}. Creator share remains 70%.`,req.user.id);res.json({ok:true,enabled,creator_share_percent:share/100})}catch(e){res.status(500).json({message:e.message})}});
app.get('/api/admin/monetization/summary',adminOnly,async(req,res)=>{if(!pool)return res.status(503).json({message:'Database is not connected on the server'});try{const [t,u,d,w]=await Promise.all([pool.query(`SELECT COALESCE(SUM(gross_paise),0) gross_paise,COALESCE(SUM(creator_paise),0) creator_paise,COALESCE(SUM(hyper_paise),0) hyper_paise,COALESCE(SUM(impressions),0) impressions,COUNT(*)::int events FROM ad_revenue_ledger`),pool.query(`SELECT u.id,u.username,COALESCE(u.channel_name,u.display_name,u.username) channel_name,COALESCE(SUM(l.gross_paise),0) gross_paise,COALESCE(SUM(l.creator_paise),0) creator_paise,COALESCE(SUM(l.hyper_paise),0) hyper_paise,COALESCE(SUM(l.impressions),0) impressions FROM users u LEFT JOIN ad_revenue_ledger l ON l.user_id=u.id GROUP BY u.id,u.username,u.channel_name,u.display_name HAVING COUNT(l.id)>0 ORDER BY hyper_paise DESC LIMIT 200`),pool.query(`SELECT DATE_TRUNC('day',created_at)::date AS "day",COALESCE(SUM(gross_paise),0) gross_paise,COALESCE(SUM(creator_paise),0) creator_paise,COALESCE(SUM(hyper_paise),0) hyper_paise FROM ad_revenue_ledger GROUP BY 1 ORDER BY 1 DESC LIMIT 90`),pool.query(`SELECT balance_paise,lifetime_earned_paise,paid_out_paise FROM hyper_admin_wallet WHERE id=1`)]);let x=t.rows[0],a=w.rows[0]||{balance_paise:0,lifetime_earned_paise:0,paid_out_paise:0};res.json({split:{creator_percent:70,hyper_admin_percent:30},wallet:{balance:Number(a.balance_paise||0)/100,lifetime_earned:Number(a.lifetime_earned_paise||0)/100,paid_out:Number(a.paid_out_paise||0)/100},totals:{gross:Number(x.gross_paise)/100,creator:Number(x.creator_paise)/100,hyper_admin:Number(x.hyper_paise)/100,impressions:Number(x.impressions||0),events:Number(x.events||0)},creators:u.rows.map(r=>({id:r.id,username:r.username,channel_name:r.channel_name,gross:Number(r.gross_paise)/100,creator:Number(r.creator_paise)/100,hyper_admin:Number(r.hyper_paise)/100,impressions:Number(r.impressions||0)})),daily:d.rows.map(r=>({day:r.day,gross:Number(r.gross_paise)/100,creator:Number(r.creator_paise)/100,hyper_admin:Number(r.hyper_paise)/100}))})}catch(e){res.status(500).json({message:e.message})}});
app.post('/api/admin/monetization/revenue',adminOnly,async(req,res)=>{if(!pool)return res.status(503).json({message:'Database is not connected on the server'});const client=await pool.connect();try{const uid=Number(req.body.user_id),gross=moneyPaise(req.body.gross_paise),impressions=Math.max(0,Number(req.body.impressions||0)),provider=String(req.body.provider||'ad-network').slice(0,40),external=String(req.body.external_event_id||'').trim(),videoId=req.body.video_id?Number(req.body.video_id):null;if(!uid||gross<=0||!external)return res.status(400).json({message:'user_id, gross_paise and external_event_id are required'});await client.query('BEGIN');await client.query('SELECT pg_advisory_xact_lock($1)',[uid]);await ensureWallet(uid);let w=(await client.query('SELECT enabled,creator_share_bps FROM creator_wallets WHERE user_id=$1 FOR UPDATE',[uid])).rows[0];if(!w?.enabled)return res.status(400).json({message:'Creator monetization is not enabled'});let creator=Math.floor(gross*Number(w.creator_share_bps)/10000),hyper=gross-creator;const ins=await client.query(`INSERT INTO ad_revenue_ledger(user_id,video_id,provider,external_event_id,gross_paise,creator_paise,hyper_paise,impressions) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(external_event_id) DO NOTHING RETURNING id`,[uid,videoId,provider,external,gross,creator,hyper,impressions]);if(ins.rowCount){await client.query('UPDATE creator_wallets SET balance_paise=balance_paise+$1,lifetime_earned_paise=lifetime_earned_paise+$1,updated_at=NOW() WHERE user_id=$2',[creator,uid]);await client.query('UPDATE hyper_admin_wallet SET balance_paise=balance_paise+$1,lifetime_earned_paise=lifetime_earned_paise+$1,updated_at=NOW() WHERE id=1',[hyper])}await client.query('COMMIT');res.json({ok:true,credited:!!ins.rowCount,creator_paise:creator,hyper_paise:hyper})}catch(e){try{await client.query('ROLLBACK')}catch{}res.status(500).json({message:e.message})}finally{client.release()}});
app.get('/api/videos/:id/comments',async(req,res)=>{if(!pool)return res.json([]);try{let q=await pool.query('SELECT c.id,c.text,c.created_at,u.display_name FROM comments c JOIN users u ON u.id=c.user_id WHERE c.video_id=$1 ORDER BY c.created_at DESC LIMIT 100',[req.params.id]);res.json(q.rows)}catch(e){res.status(500).json({message:e.message})}});
app.post('/api/videos/:id/comments',auth,async(req,res)=>{if(!pool)return res.status(503).json({message:'Database is not connected on the server'});try{let q=await pool.query('INSERT INTO comments(video_id,user_id,text) VALUES($1,$2,$3) RETURNING id,text,created_at',[req.params.id,req.user.id,String(req.body.text||'').trim()]);res.json(q.rows[0])}catch(e){res.status(500).json({message:e.message})}});
app.use((err,req,res,next)=>{if(err instanceof multer.MulterError){return res.status(400).json({message:err.code==='LIMIT_FILE_SIZE'?'Video is too large (max 250 MB).':err.message})}if(err)return res.status(400).json({message:err.message||'Upload failed'});next()});
app.get(['/studio','/studio.html'],(req,res)=>res.sendFile(path.join(__dirname,'studio.html')));
app.get(['/admin','/admin.html'],(req,res)=>res.sendFile(path.join(__dirname,'admin.html')));
app.get('*',(req,res)=>{if(req.path.startsWith('/api/'))return res.status(404).end();res.sendFile(path.join(__dirname,'index.html'))});
db().then(()=>app.listen(PORT,'0.0.0.0',()=>console.log('HYPER on '+PORT))).catch(e=>{console.error(e);app.listen(PORT,'0.0.0.0',()=>console.log('HYPER on '+PORT+' without DB'))});
