const DB='hyper-upload-queue', STORE='tasks';
self.addEventListener('install',e=>e.waitUntil(self.skipWaiting()));
self.addEventListener('activate',e=>e.waitUntil(self.clients.claim()));
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,2);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:'id'});};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function all(){const db=await openDB();return new Promise((res,rej)=>{const t=db.transaction(STORE,'readonly').objectStore(STORE).getAll();t.onsuccess=()=>res(t.result);t.onerror=()=>rej(t.error)})}
async function put(x){const db=await openDB();return new Promise((res,rej)=>{const t=db.transaction(STORE,'readwrite');t.objectStore(STORE).put(x);t.oncomplete=res;t.onerror=()=>rej(t.error)})}
async function syncUploads(){for(const x of await all()){if(x.state==='done')continue;try{await put({...x,state:'running'});const f=x.file;const d=new FormData();d.append('title',x.title);d.append('description',x.description||'');d.append('type',x.type||'video');d.append('category',x.category||'Discover');d.append('upload_id',String(x.upload_id||x.id));d.append('duration_seconds',String(x.duration_seconds||0));d.append('video',f,x.filename||f.name);if(x.thumbnail)d.append('thumbnail',x.thumbnail,x.thumbnailName||x.thumbnail.name);const r=await fetch('/api/videos',{method:'POST',headers:{Authorization:'Bearer '+x.token},body:d});if(r.ok){await put({...x,state:'done',serverResult:await r.clone().json().catch(()=>null)});const cs=await self.clients.matchAll({type:'window',includeUncontrolled:true});cs.forEach(c=>c.postMessage({type:'HYPER_UPLOAD_DONE',id:x.id}))}else{await put({...x,state:'waiting',error:'Publish failed'});throw new Error('Publish failed')}}catch(e){await put({...x,state:'waiting',error:String(e.message||e)});throw e}}}
self.addEventListener('sync',e=>{if(e.tag==='hyper-upload')e.waitUntil(syncUploads().catch(()=>{}))});
self.addEventListener('message',e=>{if(e.data?.type==='HYPER_SYNC')e.waitUntil?.(syncUploads().catch(()=>{}));});
